<script lang="ts">
	import smokeShader from '$lib/compute/kernels/smoke.wgsl?raw';

	export let data: {
		datasets: string[];
	};

	const shaderLineCount = smokeShader.trim().split('\n').length;
</script>

<main>
	<section class="hero">
		<p class="eyebrow">Migration branch</p>
		<h1>Shriveling world</h1>
		<p>
			Application shell backed by the new domain and application layers. The first non-test screen
			is now the dataset workspace, while the validation routes remain available for the CPU
			reference pipeline.
		</p>
	</section>

	<section class="checks">
		<h2>Build checks</h2>
		<ul>
			<li>SvelteKit route is active.</li>
			<li>WGSL source import works through Vite <code>?raw</code>.</li>
			<li>Smoke shader loaded with {shaderLineCount} lines.</li>
			<li>Datasets are generated by <code>npm run build:datasets</code>.</li>
			<li>Shared dataset catalog available in the root layout.</li>
		</ul>
	</section>

	<section class="nav-grid">
		<article class="panel">
			<p class="eyebrow">Application route</p>
			<h2>Dataset workspace</h2>
			<p>
				Business-oriented workspace screen built on the shared orchestration layer. It exposes
				datasets, modes, city previews, free fields, and diagnostics as application data.
			</p>
			<p><strong>{data.datasets.length}</strong> bundled datasets available.</p>
			<a class="cta" href="/workspace">Open dataset workspace</a>
		</article>

		<article class="panel">
			<p class="eyebrow">Validation routes</p>
			<h2>CPU reference benches</h2>
			<p>
				Stage-by-stage inspection routes for ingestion, GeoJSON preparation, and cone precompute.
			</p>
			<ul>
				<li><a href="/test/test1">test1</a></li>
				<li><a href="/test/test2">test2</a></li>
				<li><a href="/test/test3">test3</a></li>
			</ul>
			<a class="cta" href="/test">Open validation bench</a>
		</article>
	</section>
</main>

<style>
	main {
		min-height: 100vh;
		gap: 2rem;
		padding: 3rem;
		background:
			radial-gradient(circle at top left, rgba(13, 111, 115, 0.18), transparent 24rem),
			radial-gradient(circle at top right, rgba(119, 92, 176, 0.14), transparent 26rem),
			linear-gradient(180deg, rgba(255, 255, 255, 0.03) 0%, rgba(255, 255, 255, 0.01) 100%);
	}

	section {
		max-width: 960px;
	}

	.eyebrow {
		font-size: 0.8rem;
		letter-spacing: 0.16em;
		text-transform: uppercase;
		color: #8dd8d5;
	}

	h1 {
		margin: 0;
		font-size: clamp(3rem, 10vw, 7rem);
		line-height: 0.9;
	}

	h2 {
		margin-top: 0;
	}

	.checks {
		padding: 1.5rem;
		border: 1px solid rgba(138, 174, 188, 0.22);
		background: rgba(12, 19, 26, 0.72);
		backdrop-filter: blur(14px);
	}

	.nav-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
		gap: 1rem;
	}

	.panel {
		padding: 1.2rem;
		border: 1px solid rgba(138, 174, 188, 0.22);
		background: rgba(12, 19, 26, 0.72);
		backdrop-filter: blur(14px);
	}

	.cta {
		display: inline-block;
		margin-top: 0.75rem;
		color: #88e0dc;
		font-weight: 700;
	}
</style>
