<script lang="ts">
	import { onMount } from 'svelte';
	import smokeShader from '$lib/compute/kernels/smoke.wgsl?raw';
	import {
		loadDatasetWorkspace,
		type DatasetWorkspaceSnapshot,
	} from '$lib/application/workspace';

	export let data: {
		datasets: string[];
	};

	const shaderLineCount = smokeShader.trim().split('\n').length;
	let selectedDataset = data.datasets[0] ?? '';
	let workspace: DatasetWorkspaceSnapshot | null = null;
	let loading = false;
	let errorMessage = '';

	onMount(() => {
		if (selectedDataset) {
			void reloadWorkspace();
		}
	});

	async function reloadWorkspace(): Promise<void> {
		if (!selectedDataset) {
			return;
		}

		loading = true;
		errorMessage = '';
		try {
			workspace = await loadDatasetWorkspace(fetch, selectedDataset);
		} catch (error) {
			workspace = null;
			errorMessage = error instanceof Error ? error.message : String(error);
		} finally {
			loading = false;
		}
	}
</script>

<main>
	<section class="hero">
		<p class="eyebrow">Migration branch</p>
		<h1>Shriveling world</h1>
		<p>
			Application shell backed by the new domain and application layers. The next routes can now
			reuse a common dataset workspace instead of rebuilding orchestration glue page by page.
		</p>
	</section>

	<section class="checks">
		<h2>Build checks</h2>
		<ul>
			<li>SvelteKit route is active.</li>
			<li>WGSL source import works through Vite <code>?raw</code>.</li>
			<li>Smoke shader loaded with {shaderLineCount} lines.</li>
			<li>Datasets are generated by <code>npm run build:datasets</code>.</li>
			<li>Shared dataset catalog available in the root layout.</li>
		</ul>
	</section>

	<section class="workspace">
		<div class="workspace-head">
			<div>
				<p class="eyebrow">Shared workspace</p>
				<h2>Dataset orchestration for future screens</h2>
				<p>
					This is no longer a pure smoke page. It exercises the common application workspace that
					will feed future non-test routes.
				</p>
			</div>

			<div class="controls">
				<label>
					<span>Bundled dataset</span>
					<select bind:value={selectedDataset} on:change={() => void reloadWorkspace()}>
						{#each data.datasets as datasetName}
							<option value={datasetName}>{datasetName}</option>
						{/each}
					</select>
				</label>
				<button on:click={() => void reloadWorkspace()} disabled={loading}>
					{loading ? 'Loading...' : 'Reload workspace'}
				</button>
			</div>
		</div>

		{#if errorMessage}
			<article class="panel error">
				<h3>Workspace error</h3>
				<pre>{errorMessage}</pre>
			</article>
		{/if}

		{#if workspace}
			<div class="workspace-grid">
				<article class="panel">
					<h3>Dataset</h3>
					<p><strong>Name:</strong> {workspace.datasetName}</p>
					<p><strong>Source files:</strong> {workspace.files.length}</p>
					<p><strong>GeoJSON files:</strong> {workspace.geojsonEntries.length}</p>
				</article>

				<article class="panel">
					<h3>Domain pipeline</h3>
					<p><strong>Cities:</strong> {workspace.pipeline.preparedDataset.cityCount}</p>
					<p><strong>Edges:</strong> {workspace.pipeline.preparedDataset.edgeCount}</p>
					<p><strong>Modes:</strong> {workspace.pipeline.preparedDataset.modeCount}</p>
				</article>

				<article class="panel">
					<h3>Historical span</h3>
					<p>
						<strong>Years:</strong>
						{workspace.pipeline.preparedDataset.speedTimeline.span.beginYear} to
						{workspace.pipeline.preparedDataset.speedTimeline.span.endYear}
					</p>
					<p><strong>Queryable fields:</strong> {workspace.pipeline.baseNetwork.fields.length}</p>
				</article>
			</div>

			<div class="workspace-grid">
				<article class="panel">
					<h3>Manifest diagnostics</h3>
					<pre>{JSON.stringify(workspace.pipeline.manifest.diagnostics, null, 2)}</pre>
				</article>

				<article class="panel">
					<h3>Next validation routes</h3>
					<ul>
						<li><a href="/test/test1">test1</a>: dataset, manifest, prepared buffers, boundary limits</li>
						<li><a href="/test/test2">test2</a>: GeoJSON contours and country meshes</li>
						<li><a href="/test/test3">test3</a>: static, dynamic, raw and intersected CPU cones</li>
					</ul>
				</article>
			</div>
		{/if}
	</section>
</main>

<style>
	:global(body) {
		margin: 0;
		font-family: Georgia, 'Times New Roman', serif;
		background: #f2efe7;
		color: #1f2a24;
	}

	main {
		min-height: 100vh;
		gap: 2rem;
		padding: 3rem;
		background:
			radial-gradient(circle at top left, rgba(13, 111, 115, 0.12), transparent 24rem),
			linear-gradient(180deg, #f2efe7 0%, #ecefe8 100%);
	}

	section {
		max-width: 960px;
	}

	.eyebrow {
		font-size: 0.8rem;
		letter-spacing: 0.16em;
		text-transform: uppercase;
		color: #71644d;
	}

	h1 {
		margin: 0;
		font-size: clamp(3rem, 10vw, 7rem);
		line-height: 0.9;
	}

	h2 {
		margin-top: 0;
	}

	.checks {
		padding: 1.5rem;
		border: 1px solid #c8b99b;
		background: rgba(255, 255, 255, 0.45);
	}

	.workspace {
		display: grid;
		gap: 1rem;
	}

	.workspace-head {
		display: grid;
		gap: 1rem;
		padding: 1.5rem;
		border: 1px solid #c8b99b;
		background: rgba(255, 255, 255, 0.45);
	}

	.controls {
		display: flex;
		flex-wrap: wrap;
		gap: 1rem;
		align-items: end;
	}

	label {
		display: grid;
		gap: 0.35rem;
		min-width: 16rem;
	}

	select,
	button {
		padding: 0.7rem 0.8rem;
		border: 1px solid #c8b99b;
		border-radius: 0.8rem;
		background: rgba(255, 255, 255, 0.92);
	}

	button {
		cursor: pointer;
		font-weight: 700;
	}

	.workspace-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
		gap: 1rem;
	}

	.panel {
		padding: 1.2rem;
		border: 1px solid #c8b99b;
		background: rgba(255, 255, 255, 0.62);
	}

	.error {
		border-color: #b05f4b;
		background: rgba(255, 243, 239, 0.84);
	}

	code {
		font-family: 'Courier New', monospace;
	}

	pre {
		overflow: auto;
		white-space: pre-wrap;
	}
</style>
