<script lang="ts">
	import smokeShader from '$lib/compute/kernels/smoke.wgsl?raw';

	const shaderLineCount = smokeShader.trim().split('\n').length;
</script>

<main>
	<section>
		<p class="eyebrow">Migration branch</p>
		<h1>Shriveling world</h1>
		<p>
			Minimal SvelteKit shell. The current goal is to validate the technical foundation before
			porting rendering or computation.
		</p>
	</section>

	<section class="checks">
		<h2>Build checks</h2>
		<ul>
			<li>SvelteKit route is active.</li>
			<li>WGSL source import works through Vite <code>?raw</code>.</li>
			<li>Smoke shader loaded with {shaderLineCount} lines.</li>
			<li>Datasets are generated by <code>npm run build:datasets</code>.</li>
		</ul>
	</section>
</main>

<style>
	:global(body) {
		margin: 0;
		font-family: Georgia, 'Times New Roman', serif;
		background: #f2efe7;
		color: #1f2a24;
	}

	main {
		min-height: 100vh;
		display: grid;
		place-content: center;
		gap: 2rem;
		padding: 3rem;
	}

	section {
		max-width: 760px;
	}

	.eyebrow {
		font-size: 0.8rem;
		letter-spacing: 0.16em;
		text-transform: uppercase;
		color: #71644d;
	}

	h1 {
		margin: 0;
		font-size: clamp(3rem, 10vw, 7rem);
		line-height: 0.9;
	}

	h2 {
		margin-top: 0;
	}

	.checks {
		padding: 1.5rem;
		border: 1px solid #c8b99b;
		background: rgba(255, 255, 255, 0.45);
	}

	code {
		font-family: 'Courier New', monospace;
	}
</style>

